#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'lidar-only-cone-detector==0.1.2','console_scripts','circle_approximation_detector'
__requires__ = 'lidar-only-cone-detector==0.1.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('lidar-only-cone-detector==0.1.2', 'console_scripts', 'circle_approximation_detector')()
    )
