#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'path-followers==3.1.0','console_scripts','pure_pursuit_f1tenth'
__requires__ = 'path-followers==3.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('path-followers==3.1.0', 'console_scripts', 'pure_pursuit_f1tenth')()
    )
