#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'path-generators==1.2.2','console_scripts','example_generator'
__requires__ = 'path-generators==1.2.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('path-generators==1.2.2', 'console_scripts', 'example_generator')()
    )
